apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-mongo.fullname" . }}-config
  labels:
      app: {{ include "spring-boot-mongo.fullname" . }}-config
data:
  {{ .Values.volumeMounts.configSubPath }}: |
    server:
      servlet:
        contextPath: {{ .Values.config.contextPath }}
    spring:
      data:
        mongodb:
          host: {{ .Values.config.mongodbhost }}
          port: {{ .Values.config.mongodbport }}
          database: {{ .Values.config.mongodbdatabase }}