apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "spring-boot-mongo.fullname" . }}-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.appServer.contextPath }}
        backend:
          serviceName: {{ include "spring-boot-mongo.fullname" . }}-service
          servicePort: 8080      